=== FinnishCustoms-SuomenTulli/MIGs/Constraints.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- W3C Schema generated by XMLSpy v2021 rel. 3 (x64) (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Code">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="20"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="DescriptionEn">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="4000"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="RC">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Code"/>
				<xs:element ref="DescriptionEn" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="RulesCondition">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="RC" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== FinnishCustoms-SuomenTulli/MIGs/Export/common/constraints.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<RulesCondition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Constraints.xsd">
	<RC>
		<Code>B1003</Code>
		<DescriptionEn>In case of 'Road Transport' if the road vehicle (and/or its road trailers) are different to those declared in the initial declaration message, then they will be reported as discrepancies and not as new transport means.</DescriptionEn>
	</RC>
	<RC>
		<Code>B1201</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt; 
THEN /CD518C/GoodsShipment/DepartureTransportMeans/identificationNumber
format shall be set to an..27</DescriptionEn>
	</RC>
	<RC>
		<Code>B1202</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN
/CD518C/GoodsShipment/SupportingDocument/referenceNumber AND
/CD518C/GoodsShipment/AdditionalReference/referenceNumber AND
/CD518C/GoodsShipment /GoodsItem/TransportDocument/referenceNumber AND
/CD518C/GoodsShipment/GoodsItem/SupportingDocument/referenceNumber AND
/CD518C/GoodsShipment/GoodsItem/AdditionalReference/referenceNumber
format shall be set to an..35</DescriptionEn>
	</RC>
	<RC>
		<Code>B1203</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt; 
THEN
/CD518C/GoodsShipment/GoodsItem/Packaging/shippingMarks
format shall be set to an..42</DescriptionEn>
	</RC>
	<RC>
		<Code>B1204</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN
/CD518C/GoodsShipment/GoodsItem/Commodity/GoodsMeasure/grossMass AND
/CD518C/GoodsShipment/GoodsItem/Commodity/GoodsMeasure/netMass AND
/CD518C/GoodsShipment/Consignment/grossMass
format shall be set to n..11,3</DescriptionEn>
	</RC>
	<RC>
		<Code>B1401</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt; 
THEN  
for each Goods Item, the cumulated number of all instances of  
/CD518C/GoodsShipment/GoodsItem/SupportingDocument AND  
/CD518C/GoodsShipment/GoodsItem/TransportDocument AND 
/CD518C/GoodsShipment/GoodsItem/AdditionalReference 
shall be LESS OR EQUAL to '99x' </DescriptionEn>
	</RC>
	<RC>
		<Code>B1801</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0592 attached to /*/CurrencyExchange will be disabled
and the data group will become optional.</DescriptionEn>
	</RC>
	<RC>
		<Code>B1803</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0211 attached to /*/GoodsShipment/Consignment/CountryOfRoutingOfConsignment shall be disabled 
AND /*/GoodsShipment/Consignment/CountryOfRoutingOfConsignment = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1807</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0392 attached to /*/GoodsShipment/Consignment/LocationOfGoods shall be disabled 
AND /*/GoodsShipment/Consignment/LocationOfGoods = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1808</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN
          IF /*/GoodsShipment/GoodsItem/Procedure/requestedProcedure is in SET {76, 77} OR /*/GoodsShipment/GoodsItem/Procedure/previousProcedure is in SET {71, 78}
           THEN
                    IF /*/GoodsShipment/Consignment/grossMass is PRESENT
                    THEN /*/GoodsShipment/GoodsItem/GoodsMeasure/grossMass = "O"
                    ELSE /*/GoodsShipment/GoodsItem/GoodsMeasure/grossMass = "R"
            ELSE /*/GoodsShipment/GoodsItem/GoodsMeasure/grossMass = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1810</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0273 attached to
/*/GoodsShipment/natureOfTransaction
shall be disabled.</DescriptionEn>
	</RC>
	<RC>
		<Code>B1812</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0237 attached to /*/CustomsOfficeOfDestination 
shall be disabled
AND /*/CustomsOfficeOfDestination = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1816</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN R0855 attached to 
/*/GoodsShipment/Consignment/DepartureTransportMeans 
shall be disabled</DescriptionEn>
	</RC>
	<RC>
		<Code>B1817</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0273 attached to /*/GoodsShipment/countryOfExport
shall be disabled
AND /*/GoodsShipment/countryOfExport = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1818</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0890 attached to /*/GoodsShipment/Consignment/ActiveBorderTransportMeans shall be disabled 
AND /*/GoodsShipment/Consignment/ActiveBorderTransportMeans = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1824</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN R0995 attached to /*/Exporter/identificationNumber shall be disabled</DescriptionEn>
	</RC>
	<RC>
		<Code>B1826</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than OR EQUAL to &lt;TPendDate&gt;
THEN C0834 attached to /*/GoodsShipment/Consignment/DepartureTransportMeans
shall be disabled AND /*/GoodsShipment/Consignment/DepartureTransportMeans = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1828</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0259 attached to /*/GoodsShipment/GoodsItem/countryOfExport
shall be disabled</DescriptionEn>
	</RC>
	<RC>
		<Code>B1829</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS OR EQUAL to &lt;TPendDate&gt; 
THEN C0864 attached to /*/GoodsShipment/SupportingDocument shall be disabled.</DescriptionEn>
	</RC>
	<RC>
		<Code>B1830</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS OR EQUAL to &lt;TPendDate&gt;
THEN
        IF /*/ExportOperation/transit is EQUAL to '1'
        THEN /*/GoodsShipment/SupportingDocument = "R"
        ELSE /*/GoodsShipment/SupportingDocument = "N"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1833</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0511 attached to /*/correlationIdentifier shall be disabled
AND /*/correlationIdentifier = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1837</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN
	IF /*/GoodsShipment/countryOfDestination is PRESENT
     THEN /*/GoodsShipment/GoodsItem/countryOfDestination = "N" 
ELSE IF /*/GoodsShipment/GoodsItem/Procedure/previousProcedure is in SET {71,78}
     THEN /*/GoodsShipment/GoodsItem/countryOfDestination = "O" 
		ELSE /*/GoodsShipment/GoodsItem/countryOfDestination = "R"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1838</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0503 attached to
/*/GoodsShipment/countryOfDestination shall be disabled
AND /*/GoodsShipment/countryOfDestination = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1839</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;   
THEN 
	IF /*/ExportOperation/requestRejectionReasonCode is PRESENT
    THEN /*/ExportOperation/additionalDeclarationType = "N"
       AND NO validation of other conditions is performed
	ELSE /*/ExportOperation/additionalDeclarationType = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1840</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0365 attached to 
/*/ExportOperation/additionalDeclarationType
shall be disabled</DescriptionEn>
	</RC>
	<RC>
		<Code>B1841</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt; 
THEN C0374 attached to 
/*/GoodsShipment/Consignment/modeOfTransportAtTheBorder
shall be disabled.</DescriptionEn>
	</RC>
	<RC>
		<Code>B1842</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than OR EQUAL to &lt;TPendDate&gt;
THEN
        IF /*/ExportOperation/additionalDeclarationType is in SET {B, C, E, F}
        THEN /*/GoodsShipment/Consignment/modeOfTransportAtTheBorder = "N"
        ELSE /*/GoodsShipment/Consignment/modeOfTransportAtTheBorder = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1844</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN
          IF /*/GoodsShipment/GoodsItem/Procedure/requestedProcedure is in SET {76, 77} OR /*/GoodsShipment/GoodsItem/Procedure/previousProcedure is in SET {71, 78}
          THEN
                    IF /*/GoodsShipment/GoodsItem/GoodsMeasure/grossMass is PRESENT
                    THEN /*/GoodsShipment/Consignment/grossMass = "O"
                    ELSE /*/GoodsShipment/Consignment/grossMass = "R"
           ELSE /*/GoodsShipment/Consignment/grossMass = "O"</DescriptionEn>
	</RC>
	<RC>
		<Code>B1846</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN R0840 attached to 
/*/GoodsShipment/Consignment/Consignee/identificationNumber AND
/*/GoodsShipment/GoodsItem/Consignee/identificationNumber
shall be disabled
</DescriptionEn>
	</RC>
	<RC>
		<Code>B1855</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN 
          IF /*/GoodsShipment/countryOfExport is PRESENT
          THEN /*/GoodsShipment/GoodsItem/countryOfExport = “N”
          ELSE
                  IF (/CC515C/ExportOperation/specificCircumstanceIndicator is EQUAL to ‘A20’ OR /CC513C/ExportOperation/specificCircumstanceIndicator is EQUAL to ‘A20’)
                  THEN /*/GoodsShipment/GoodsItem/countryOfExport = ”O”
                  ELSE /*/GoodsShipment/GoodsItem/countryOfExport = “R”</DescriptionEn>
	</RC>
	<RC>
		<Code>B1856</Code>
		<DescriptionEn>IF &lt;Decisive Date&gt; is LESS than or EQUAL to &lt;TPendDate&gt;
THEN C0375 attached to
/*/GoodsShipment/natureOfTransaction shall be disabled.</DescriptionEn>
	</RC>
	<RC>
