=== FinnishCustoms-SuomenTulli/MIGs/Messageexchange.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 (x64) (http://www.altova.com) by Finnish Customs (Finnish Customs) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" xmlns:altova="http://www.altova.com/xml-schema-extensions" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="MessageExchange" type="MessageExchangeType"/>
	<xs:complexType name="MessagesType">
		<xs:sequence maxOccurs="unbounded">
			<xs:element name="Message">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Sender">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="EO|Customs"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="ID"/>
						<xs:element name="Name" maxOccurs="3">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="lang" use="required">
											<xs:annotation>
												<xs:appinfo>
													<altova:exampleValues>
														<altova:example value="fi|sv|en"/>
													</altova:exampleValues>
												</xs:appinfo>
											</xs:annotation>
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="DescriptionLine" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="lang" use="required">
											<xs:annotation>
												<xs:appinfo>
													<altova:exampleValues>
														<altova:example value="fi|sv|en"/>
													</altova:exampleValues>
												</xs:appinfo>
											</xs:annotation>
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="UseCasesType">
		<xs:sequence>
			<xs:element name="UseCase" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Name" maxOccurs="3">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="lang" use="required">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="fi|sv|en"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:attribute>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="Sequence">
							<xs:complexType>
								<xs:sequence maxOccurs="unbounded">
									<xs:element name="EO" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
									<xs:element name="Customs" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
						<xs:element name="SequenceDescription">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Item" maxOccurs="unbounded">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="ItemLine" maxOccurs="unbounded">
													<xs:complexType>
														<xs:simpleContent>
															<xs:extension base="xs:string">
																<xs:attribute name="lang" use="required">
																	<xs:simpleType>
																		<xs:restriction base="xs:string">
																			<xs:pattern value="fi|sv|en"/>
																		</xs:restriction>
																	</xs:simpleType>
																</xs:attribute>
															</xs:extension>
														</xs:simpleContent>
													</xs:complexType>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="MessageExchangeType">
		<xs:sequence>
			<xs:element name="Messages" type="MessagesType" maxOccurs="unbounded"/>
			<xs:element name="UseCases" type="UseCasesType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== FinnishCustoms-SuomenTulli/MIGs/customswarehousing/common/messageexchange.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 (x64) (http://www.altova.com) by Finnish Customs (Finnish Customs) -->
<MessageExchange xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../MessageExchange.xsd">
	<Intro>
		<TextLine lang="fi">Tullivarastoinnin sanomat lähetetään suorana sanoma-asiointina ja ne käsitellään Tullissa UTU-järjestelmässä. UTU-järjestelmä on Suomen tullin uusi tulliselvitysjärjestelmä, joka otetaan käyttöön vaiheittain Unionin tullikoodeksin mukaisessa aikataulussa. Ilmoitusten käsittely tapahtuu pääasiassa automaattisesti UTU-järjestelmässä. Manuaalikäsittelyä vaativat ilmoitukset käsitellään Sähköisessä palvelukeskuksessa.</TextLine>
		<TextLine lang="sv">Meddelandena för tullagring skickas som direkt meddelandedeklarering och handläggs vid Tullen i UTU-systemet. UTU-systemet är Finska tullens nya tullklareringssystem som tas i bruk i etapper enligt tidtabellen i unionstullkodexen. Handläggningen av deklarationerna sker huvudsakligen automatiskt i UTU-systemet. Deklarationer som kräver manuell handläggning handläggs vid Elektroniska servicecentralen.</TextLine>
		<TextLine lang="fi">Tässä sanomaliikenneoppaassa kuvataan tullivarastoinnin ilmoitusten ja tiedonantojen sanomaliikenteen perusperiaatteet ilmoituksen lähettäjän ja Tullin välillä. Kuvauksessa on listattu sanomat, jotka asiakas voi lähettää Tullille, sekä sanomat, jotka asiakas voi saada Tullilta. Kuvaukseen on koottu esimerkkejä tyypillisimmistä sanomaliikenteen käyttötapauksista. Käytännön tilanteissa voi esiintyä erilaisia yhdistelmiä tämän oppaan esimerkeistä.</TextLine>
		<TextLine lang="sv">I denna guide för meddelandetrafik beskrivs grundprinciperna för meddelandetrafiken mellan deklaranten och Tullen i fråga om meddelanden och anmälningar för tullagring. Guiden omfattar meddelandena som kunden kan skicka till Tullen och meddelandena som Tullen kan skicka till kunden. I guiden ges exempel på de vanligaste situationerna i meddelandetrafiken. I praktiken kan olika kombinationer av exemplen i guiden förekomma.</TextLine>
		<TextLine lang="fi">Tullivarastoinnin sanomaliikenne voi liittyä joko:</TextLine>
		<TextLine lang="sv">Meddelandetrafiken för tullagring kan hänföra sig till:</TextLine>
		<List>
			<ListItem lang="fi">tavaroiden asettamiseen tullivarastointimenettelyyn vakiomuotoisella ilmoituksella,</ListItem>
			<ListItem lang="sv">hänförande av varor till tullagerförfarandet med en standardtulldeklaration,</ListItem>
			<ListItem lang="fi">tavaroiden asettamiseen tullivarastointimenettelyyn toimijan kirjanpitoon tehtävällä merkinnällä, joka edellyttää esittämistiedonantoa</ListItem>
			<ListItem lang="sv">hänförande av varor till tullagerförfarandet genom en registrering i aktörens bokföring, vilket kräver en anmälan av varors ankomst, eller</ListItem>
			<ListItem lang="fi">tullivarastoinnin päättämistiedonantoon</ListItem>
			<ListItem lang="sv">anmälan om avslutande av tullagerförfarandet.</ListItem>
		</List>
		<TextLine lang="fi">Yllämainitut ilmoitukset saavat tullilta ilmoituksen yksilöivän viitteen, MRN:n (Master Reference Number). MRN tulee merkitä tullivarastoinnin kirjanpitoon.</TextLine>
		<TextLine lang="sv">Tullen tilldelar ovan nämnda deklarationer ett referensnummer, MRN (Master Reference Number), som specificerar deklarationen. MRN ska antecknas i tullagrets bokföring.</TextLine>
		<TextLine lang="fi">Tullin järjestelmä tarkastaa eri vaiheissa, että Tullille lähetetty ilmoitussanoma täyttää Tullin sanomarakenteelle ja –sisällölle määrittämät vaatimukset.</TextLine>
		<TextLine lang="sv">Tullens system granskar i olika skeden att deklarationsmeddelandet som skickats till Tullen uppfyller de krav som Tullen ställer på meddelandenas struktur och innehåll.</TextLine>
		<TextLine lang="fi">Tullin järjestelmä lähettää vastaussanomat samalle lähettäjälle, joka on lähettänyt sanoman Tullille.</TextLine>
		<TextLine lang="sv">Tullens system skickar svarsmeddelandena till den avsändare som skickat meddelandet till Tullen.</TextLine>
		<TextLine lang="fi">Tullivarastointi-ilmoitus on mahdollista antaa 30 päivää ennen tavaran esittämistä, jos edeltävän ilmoituksen (esim. passitus) viitenumerot ovat tiedossa.</TextLine>
		<TextLine lang="sv">Tullagerdeklarationen kan inges på förhand, 30 dagar innan varornas ankomst anmäls, om man känner till referensnumren för den föregående deklarationen (t.ex. transitering).</TextLine>
		<TextLine lang="fi">Lähettäjä voi korjata sanomaa ennen tavaran luovuttamista menettelyyn. Lähettäjä voi korjata kaikkia tietoja seuraavia poikkeuksia lukuun ottamatta: ilmoittajan tunnistetiedot, edustajan tunnistetiedot, edustusmuoto ja tullimenettely. Jos ilmoitus on jo luovutettu menettelyyn ja sitä halutaan muuttaa, sitä on oikaistava. Tullivarastoinnin ensimmäisessä vaiheessa oikaisupyyntö jätetään tullille vapaamuotoisella yhteydenottopyynnöllä.</TextLine>
		<TextLine lang="sv">Avsändaren kan korrigera meddelandet innan varorna frigörs för förfarandet. Avsändaren kan korrigera alla uppgifter förutom följande: deklarantens identifieringsuppgifter, ombudets identifieringsuppgifter, typen av ombudskap och tullförfarandet. Om man vill göra ändringar i en deklaration som redan har hänförts till förfarandet så måste man begära ändring av den. I den första fasen av tullagringen inges begäran om ändring till Tullen genom en fritt formulerad kontakt.</TextLine>
		<TextLine lang="fi">Tullin lähettämään lisäselvityspyyntöön vastataan aina sanomalla. Jos tulli pyytää liiteasiakirjoja, ne lähetetään LIITU-järjestelmään joko Tullin tarjoaman asiakaskäyttöliittymän tai asiakkaan oman järjestelmän kautta.</TextLine>
		<TextLine lang="sv">Man svarar alltid med ett meddelande på en begäran om tilläggsutredning som Tullen skickat. Om Tullen begär att få bilagor så skickas dessa till LIITU-systemet antingen via Tullens kundgränssnitt eller kundens egna system.</TextLine>
	</Intro>
	<Messages>
		<Message>
			<Sender>EO</Sender>
			<ID>FI415</ID>
			<Name lang="fi">Tullivarastointi-ilmoitus</Name>
			<Name lang="sv">Tullagerdeklaration</Name>
			<Name lang="en">Declaration for customs warehousing</Name>
			<DescriptionLine lang="fi">Asiakas lähettää Tullille asettaakseen tavarat tullivarastointimenettelyyn.</DescriptionLine>
			<DescriptionLine lang="sv">Kunden skickar detta meddelande till Tullen när denne vill hänföra varor till tullagerförfarandet.</DescriptionLine>
		</Message>
		<Message>
			<Sender>Customs</Sender>
			<ID>FI403</ID>
			<Name lang="fi">Oikaisusanoma</Name>
			<Name lang="sv">Meddelande om ändring</Name>
			<DescriptionLine lang="fi">Tulli lähettää asiakkaalle tiedon päätöksestään hyväksyä asiakkaan oikaisupyyntö (asiakasaloitteinen oikaisupyyntö).</DescriptionLine>
			<DescriptionLine lang="sv">Tullen meddelar kunden om sitt beslut att godta kundens begäran om ändring (begäran om ändring på kundens initiativ).</DescriptionLine>
			<DescriptionLine lang="fi">Tulli lähettää asiakkaalle tiedon päätöksestään oikaista ilmoituksen tai aiemman päätöksen tietoja (tullialoitteinen oikaisu).</DescriptionLine>
			<DescriptionLine lang="sv">Tullen meddelar kunden om sitt beslut att ändra uppgifter i deklarationen eller i ett tidigare beslut (ändring på Tullens initiativ).</DescriptionLine>
		</Message>
		<Message>
			<Sender>Customs</Sender>
			<ID>FI405</ID>
			<Name lang="fi">Oikaisupyynnön hylkäyssanoma</Name>
			<Name lang="sv">Meddelande om avslag på begäran om ändring</Name>
			<DescriptionLine lang="fi">Tulli lähettää asiakkaalle tiedon päätöksestään hylätä asiakkaan pyyntö oikaista ilmoituksen tietoja.</DescriptionLine>
			<DescriptionLine lang="sv">Tullen meddelar kunden om sitt beslut att avslå kundens begäran om ändring av uppgifter i deklarationen.</DescriptionLine>
		</Message>
		<Message>
			<Sender>Customs</Sender>
			<ID>FI448</ID>
			<Name lang="fi">Mitätöintipyynnön hylkäyssanoma</Name>
			<Name lang="sv">Meddelande om avslag på begäran om ogiltigförklaring</Name>
			<DescriptionLine lang="fi">Tulli lähettää asiakkaalle tiedon päätöksestään hylätä asiakkaan pyyntö mitätöidä ilmoitus.</DescriptionLine>
			<DescriptionLine lang="sv">Tullen meddelar kunden om sitt beslut att avslå kundens begäran om ogiltigförklaring av deklarationen.</DescriptionLine>
		</Message>
		<Message>
			<Sender>Customs</Sender>
			<ID>FI410</ID>
			<Name lang="fi">Mitätöintisanoma</Name>
			<Name lang="sv">Meddelande om ogiltigförklaring</Name>
			<DescriptionLine lang="fi">Tulli lähettää asiakkaalle tiedon päätöksestään hyväksyä asiakkaan mitätöintipyyntö (asiakasaloitteinen mitätöintipyyntö).</DescriptionLine>
			<DescriptionLine lang="sv">Tullen meddelar kunden om sitt beslut att godta kundens begäran om ogiltigförklaring (begäran om ogiltigförklaring på kundens initiativ).</DescriptionLine>
			<DescriptionLine lang="fi">Tulli lähettää asiakkaalle tiedon päätöksestään mitätöidä ilmoitus (tullialoitteinen mitätöinti).</DescriptionLine>
			<DescriptionLine lang="sv">Tullen meddelar kunden om sitt beslut att ogiltigförklara deklarationen (ogiltigförklaring på Tullens initiativ).</DescriptionLine>
			<DescriptionLine lang="fi">Tulli lähettää asiakkaalle tiedon luovutuksen epäämisestä (ilmoitusta ei luovuteta menettelyyn vaan luovutus evätään).</DescriptionLine>
			<DescriptionLine lang="sv">Tullen meddelar kunden om förvägrandet av frigörandet (deklarationen frigörs inte för förfarandet, utan frigörandet förvägras).</DescriptionLine>
		</Message>
		<Message>
			<Sender>EO</Sender>
			<ID>FI413</ID>
			<Name lang="fi">Korjauspyyntö</Name>
			<Name lang="sv">Begäran om korrigering</Name>
			<DescriptionLine lang="fi">Asiakas lähettää Tulliin pyynnön korjata antamansa ilmoituksen tietoja ennen tavaran luovuttamista menettelyyn.</DescriptionLine>
			<DescriptionLine lang="sv">Kunden skickar till Tullen en begäran om korrigering av uppgifterna i deklarationen som denne ingett, innan varorna frigörs för förfarandet.</DescriptionLine>
		</Message>
