=== FinnishCustoms-SuomenTulli/MIGs/Message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 rel. 3 (x64) (http://www.altova.com) by Tulli (Tulli) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Message" type="MessageType"/>
	<xs:element name="DataGroup" type="DataGroupType"/>
	<xs:element name="DataElement" type="DataElementType"/>
	<xs:complexType name="DataGroupType">
		<xs:sequence>
			<xs:element name="Name" maxOccurs="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="NameType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Alias" minOccurs="0" maxOccurs="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="NameType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Use" minOccurs="0" maxOccurs="99">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="6"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Filter" minOccurs="0" maxOccurs="99">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="XPath">
				<xs:simpleType>
					<xs:restriction base="XPathType"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Group" type="XPathType"/>
			<xs:element name="MinOccurence" maxOccurs="99">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:integer">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="MaxOccurence" maxOccurs="99">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:integer">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Rule" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ConstraintsType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Condition" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ConstraintsType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="DescriptionLine" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="DescriptionLineType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="DataElement"/>
				<xs:element ref="DataGroup" minOccurs="0"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="hidden">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="4"/>
					<xs:pattern value="true"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="DataElementType">
		<xs:sequence>
			<xs:element name="Name" maxOccurs="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="NameType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Alias" minOccurs="0" maxOccurs="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="NameType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Use" minOccurs="0" maxOccurs="99">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="6"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Filter" minOccurs="0" maxOccurs="99">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="XPath">
				<xs:simpleType>
					<xs:restriction base="XPathType"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MinOccurence" maxOccurs="99">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:integer">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Codelist" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="CodeListType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Rule" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ConstraintsType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Condition" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ConstraintsType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Format">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DescriptionLine" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="DescriptionLineType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Hyperlink" minOccurs="0" maxOccurs="99">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="URL">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:maxLength value="200"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="Description">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:maxLength value="200"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="lang" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:maxLength value="2"/>
								<xs:pattern value="fi|sv|en"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="XPathType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
			<xs:pattern value='[A-Za-z@="]*'/>
			<xs:pattern value=""/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="MessageType">
		<xs:sequence>
			<xs:element name="Type" minOccurs="0"/>
			<xs:element name="Rule" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ConstraintsType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element ref="DataGroup" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="NameType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ConstraintsType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DescriptionLineType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="2000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CodeListType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="15"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== FinnishCustoms-SuomenTulli/MIGs/common/FI439A.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 (x64) (http://www.altova.com) by Finnish Customs (Finnish Customs) -->
<Message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../Message.xsd">
	<Type>FI439A</Type>
	<Name lang="en">Free-formcontact request</Name>
	<DataGroup>
		<Name lang="en">Import operation</Name>
		<XPath>FI439A</XPath>
		<MinOccurence>1</MinOccurence>
		<MaxOccurence>1</MaxOccurence>
		<DataElement>
			<Name lang="fi">MRN</Name>
			<Name lang="sv">MRN</Name>
			<Name lang="en">MRN</Name>
			<XPath>MRN</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>MRN</GeneralType>
			<Format>an18</Format>
		</DataElement>
		<DataElement>
			<Name lang="fi">LRN</Name>
			<Name lang="sv">LRN</Name>
			<Name lang="en">LRN</Name>
			<XPath>FunctionalReference</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>LRN</GeneralType>
			<Format>an..22</Format>
		</DataElement>
		<DataElement>
			<Name lang="en">Additional LRN</Name>
			<XPath>AdditionalFunctionalReference</XPath>
			<MinOccurence>0</MinOccurence>
			<GeneralType>LRN</GeneralType>
			<Format>an..22</Format>
		</DataElement>
		<DataElement>
			<Name lang="en">MessageIdentification</Name>
			<XPath>Identification</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>MessageIdentification</GeneralType>
			<Format>an..14</Format>
		</DataElement>
		<DataElement>
			<Name lang="fi">Kielikoodi</Name>
			<Name lang="sv">Sprì±…kkod</Name>
			<Name lang="en">Language code</Name>
			<XPath>Language</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>LanguageCode</GeneralType>
			<Codelist>CL012</Codelist>
			<Format>a2</Format>
		</DataElement>
		<DataGroup>
			<Name lang="en">Notification</Name>
			<XPath>Notification</XPath>
			<MinOccurence>1</MinOccurence>
			<MaxOccurence>1</MaxOccurence>
			<DataElement>
				<Name lang="en">Notification type</Name>
				<XPath>Type</XPath>
				<MinOccurence>1</MinOccurence>
				<GeneralType>LanguageCode</GeneralType>
				<Format>an..100</Format>
			</DataElement>
			<DataElement>
				<Name lang="en">Notification date and time</Name>
				<XPath>Notification</XPath>
				<MinOccurence>1</MinOccurence>
				<GeneralType>DateTime</GeneralType>
				<Format>dateTime</Format>
			</DataElement>
			<DataElement>
				<Name lang="en">Notification description</Name>
				<XPath>Text</XPath>
				<MinOccurence>0</MinOccurence>
				<GeneralType>Freetext</GeneralType>
				<Format>an..4096</Format>
			</DataElement>
			<DataElement>
				<Name lang="en">Reason for contact</Name>
				<XPath>ContactReason</XPath>
				<MinOccurence>0</MinOccurence>
				<GeneralType>String</GeneralType>
				<Codelist>NCL050</Codelist>
				<Format>an..50</Format>
			</DataElement>
			<DataElement>
				<Name lang="en">Invalidation reason</Name>
				<XPath>Invalidation</XPath>
				<MinOccurence>0</MinOccurence>
				<GeneralType>String</GeneralType>
				<Codelist>NCL062</Codelist>
				<Format>n..50</Format>
			</DataElement>
			<DataElement>
				<Name lang="en">Amendment reason</Name>
				<XPath>Amendment</XPath>
				<MinOccurence>0</MinOccurence>
				<GeneralType>an..50</GeneralType>
				<Codelist>NCL062</Codelist>
				<Format>String</Format>
			</DataElement>
		</DataGroup>
		<DataGroup>
			<Name lang="en">Submitter</Name>
			<XPath>Submitter</XPath>
			<MinOccurence>1</MinOccurence>
			<MaxOccurence>1</MaxOccurence>
			<DataElement>
				<Name lang="en">Submitter name</Name>
				<XPath>Name</XPath>
				<MinOccurence>1</MinOccurence>
				<GeneralType>TraderName</GeneralType>
				<Format>an..70</Format>
			</DataElement>
			<DataGroup>
				<Name lang="en">Submitter e-mail</Name>
				<XPath>Communication</XPath>
				<MinOccurence>1</MinOccurence>
				<MaxOccurence>1</MaxOccurence>
				<DataElement>
					<Name lang="en">Submitter e-mail address</Name>
					<XPath>Identification</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>CommunicationIdentification</GeneralType>
					<Format>an..320</Format>
				</DataElement>
				<DataElement>
					<Name lang="en">Submitter communication type</Name>
					<XPath>Type</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>CommunicationType</GeneralType>
					<Format>a2</Format>
				</DataElement>
			</DataGroup>
			<DataGroup>
				<Name lang="en">Submitter telephone</Name>
				<XPath>Communication</XPath>
				<MinOccurence>0</MinOccurence>
				<MaxOccurence>1</MaxOccurence>
				<DataElement>
					<Name lang="en">Submitter telephone number</Name>
					<XPath>Identification</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>CommunicationIdentification</GeneralType>
					<Format>an..20</Format>
				</DataElement>
				<DataElement>
					<Name lang="en">Submitter communication type</Name>
					<XPath>Type</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>CommunicationType</GeneralType>
					<Format>a2</Format>
				</DataElement>
			</DataGroup>
		</DataGroup>
	</DataGroup>
</Message>

=== FinnishCustoms-SuomenTulli/MIGs/customswarehousing/common/FI916A.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 (x64) (http://www.altova.com) by Finnish Customs (Finnish Customs) -->
<Message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Message.xsd">
	<Type>FI916A</Type>
	<Name lang="en">Rejection notification</Name>
	<DataGroup>
		<Name lang="en">Import operation</Name>
		<XPath>FI916A</XPath>
		<MinOccurence>1</MinOccurence>
		<MaxOccurence>1</MaxOccurence>
		<DataElement>
			<Name lang="fi">MRN</Name>
			<Name lang="sv">MRN</Name>
			<Name lang="en">MRN</Name>
			<XPath>MRN</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>MRN</GeneralType>
			<Format>an18</Format>
		</DataElement>
		<DataElement>
			<Name lang="fi">LRN</Name>
			<Name lang="sv">LRN</Name>
			<Name lang="en">LRN</Name>
			<XPath>FunctionalReference</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>LRN</GeneralType>
			<Format>an..22</Format>
		</DataElement>
		<DataElement>
			<Name lang="fi">Toissijainen LRN</Name>
			<Name lang="sv">Ytterligare LRN</Name>
			<Name lang="en">LRN</Name>
			<XPath>AdditionalFunctionalReference</XPath>
			<MinOccurence>0</MinOccurence>
			<GeneralType>LRN</GeneralType>
			<Format>an..22</Format>
		</DataElement>
		<DataElement>
			<Name lang="fi">Sanoman tunniste</Name>
			<Name lang="sv">Meddelandets identifiering</Name>
			<Name lang="en">Message identification</Name>
			<XPath>Identification</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>MessageIdentification</GeneralType>
			<Format>an..14</Format>
		</DataElement>
		<DataElement>
			<Name lang="fi">Kielikoodi</Name>
			<Name lang="sv">Spr√•kkod</Name>
			<Name lang="en">Language code</Name>
			<XPath>Language</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>LanguageCode</GeneralType>
			<Codelist>CL012</Codelist>
			<Format>a2</Format>
		</DataElement>
		<DataGroup>
			<Name lang="en">Notification</Name>
			<XPath>Notification</XPath>
			<MinOccurence>1</MinOccurence>
			<MaxOccurence>1</MaxOccurence>
			<DataElement>
				<Name lang="en">Notification type</Name>
				<XPath>Type</XPath>
				<MinOccurence>1</MinOccurence>
				<GeneralType>LanguageCode</GeneralType>
				<Format>an..100</Format>
			</DataElement>
			<DataElement>
				<Name lang="en">Notification date and time</Name>
				<XPath>Notification</XPath>
				<MinOccurence>1</MinOccurence>
				<GeneralType>DateTime</GeneralType>
				<Format>dateTime</Format>
			</DataElement>
			<DataElement>
				<Name lang="en">Notification description</Name>
				<XPath>Text</XPath>
				<MinOccurence>0</MinOccurence>
				<GeneralType>Freetext</GeneralType>
				<Format>an..4096</Format>
			</DataElement>
			<DataGroup>
				<Name lang="en">Contact information</Name>
				<XPath>ContactInfo</XPath>
				<MinOccurence>1</MinOccurence>
				<MaxOccurence>1</MaxOccurence>
				<DataElement>
					<Name lang="en">Name</Name>
					<XPath>Name</XPath>
					<MinOccurence>0</MinOccurence>
					<GeneralType>TraderName</GeneralType>
					<Format>an..100</Format>
				</DataElement>
				<DataElement>
					<Name lang="en">E-mail</Name>
					<XPath>Email</XPath>
					<MinOccurence>0</MinOccurence>
					<GeneralType>String</GeneralType>
					<Format>an..320</Format>
				</DataElement>
				<DataElement>
					<Name lang="en">Telephone</Name>
					<XPath>Name</XPath>
					<MinOccurence>0</MinOccurence>
					<GeneralType>TelephoneNumber</GeneralType>
					<Format>an..20</Format>
				</DataElement>
			</DataGroup>
			<DataGroup>
				<Name lang="en">Error</Name>
				<XPath>Error</XPath>
				<MinOccurence>1</MinOccurence>
				<MaxOccurence>999</MaxOccurence>
				<DataElement>
					<Name lang="en">Error code</Name>
					<XPath>Code</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>String</GeneralType>
					<Format>an..10</Format>
				</DataElement>
				<DataElement>
					<Name lang="en">Error reason</Name>
					<XPath>Reason</XPath>
					<MinOccurence>0</MinOccurence>
					<GeneralType>String</GeneralType>
					<Format>an..4096</Format>
				</DataElement>
				<DataElement>
					<Name lang="en">Error pointer</Name>
					<XPath>Pointer/Location</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>String</GeneralType>
					<Format>an..200</Format>
				</DataElement>
				<DataElement>
					<Name lang="en">Original attribute value</Name>
					<XPath>OriginaValue</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>String</GeneralType>
					<Format>an..512</Format>
				</DataElement>
			</DataGroup>
		</DataGroup>
	</DataGroup>
</Message>
