=== FinnishCustoms-SuomenTulli/MIGs/Message.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 rel. 3 (x64) (http://www.altova.com) by Tulli (Tulli) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Message" type="MessageType"/>
	<xs:element name="DataGroup" type="DataGroupType"/>
	<xs:element name="DataElement" type="DataElementType"/>
	<xs:complexType name="DataGroupType">
		<xs:sequence>
			<xs:element name="Name" maxOccurs="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="NameType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Alias" minOccurs="0" maxOccurs="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="NameType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Use" minOccurs="0" maxOccurs="99">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="6"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Filter" minOccurs="0" maxOccurs="99">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="XPath">
				<xs:simpleType>
					<xs:restriction base="XPathType"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Group" type="XPathType"/>
			<xs:element name="MinOccurence" maxOccurs="99">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:integer">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="MaxOccurence" maxOccurs="99">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:integer">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Rule" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ConstraintsType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Condition" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ConstraintsType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="DescriptionLine" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="DescriptionLineType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="DataElement"/>
				<xs:element ref="DataGroup" minOccurs="0"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="hidden">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:maxLength value="4"/>
					<xs:pattern value="true"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="DataElementType">
		<xs:sequence>
			<xs:element name="Name" maxOccurs="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="NameType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Alias" minOccurs="0" maxOccurs="3">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="NameType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Use" minOccurs="0" maxOccurs="99">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="6"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Filter" minOccurs="0" maxOccurs="99">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="XPath">
				<xs:simpleType>
					<xs:restriction base="XPathType"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="MinOccurence" maxOccurs="99">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:integer">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Codelist" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="CodeListType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Rule" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ConstraintsType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Condition" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ConstraintsType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Format">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="10"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="DescriptionLine" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="DescriptionLineType">
							<xs:attribute name="lang" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="2"/>
										<xs:pattern value="fi|sv|en"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="Hyperlink" minOccurs="0" maxOccurs="99">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="URL">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:maxLength value="200"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="Description">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:maxLength value="200"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="lang" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:maxLength value="2"/>
								<xs:pattern value="fi|sv|en"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="XPathType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
			<xs:pattern value='[A-Za-z@="]*'/>
			<xs:pattern value=""/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="MessageType">
		<xs:sequence>
			<xs:element name="Type" minOccurs="0"/>
			<xs:element name="Rule" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="ConstraintsType">
							<xs:attribute name="use">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:maxLength value="6"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element ref="DataGroup" maxOccurs="2"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="NameType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ConstraintsType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DescriptionLineType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="2000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CodeListType">
		<xs:restriction base="xs:string">
			<xs:maxLength value="15"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== FinnishCustoms-SuomenTulli/MIGs/CourierMail/common/CourierMail.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 (x64) (http://www.altova.com) by Finnish Customs (Finnish Customs) -->
<Message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Message.xsd">
	<Type>CourierMail</Type>
	<Name lang="en">Courier and mail cargo details</Name>
	<DataGroup>
		<Name lang="en">Import operation</Name>
		<XPath>CourierMail</XPath>
		<MinOccurence>1</MinOccurence>
		<MaxOccurence>1</MaxOccurence>
		<DataElement>
			<Name lang="en">Available for clearance</Name>
			<XPath>replyType</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType/>
			<Format>n1</Format>
			<DescriptionLine lang="en">Indicator if the goods have arrived at the storage facility.</DescriptionLine>
			<DescriptionLine lang="en">Data required from 2019 onward.</DescriptionLine>
		</DataElement>
		<DataElement>
			<Name lang="en">Item ID</Name>
			<XPath>FunctionalReference@function="ItemID"</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType/>
			<Format>an..35</Format>
			<DescriptionLine lang="en">Tracking number of the parcel</DescriptionLine>
		</DataElement>
		<DataElement>
			<Name lang="fi">Bruttomassa</Name>
			<Name lang="sv">Bruttomassa</Name>
			<Name lang="en">Gross mass</Name>
			<XPath>GrossMass</XPath>
			<MinOccurence>1</MinOccurence>
			<EUCDM>6/5</EUCDM>
			<GeneralType>Decimal</GeneralType>
			<Condition>NC0601</Condition>
			<Format>n..16,6</Format>
			<DescriptionLine lang="en">Data required from 2019 onward.</DescriptionLine>
		</DataElement>
		<DataGroup>
			<Name lang="en">Exporter</Name>
			<XPath>Exporter</XPath>
			<MinOccurence>0</MinOccurence>
			<MaxOccurence>1</MaxOccurence>
			<Condition>NC0602</Condition>
			<DataElement>
				<Name lang="en">Exporter name</Name>
				<XPath>Name</XPath>
				<MinOccurence>1</MinOccurence>
				<GeneralType>TraderName</GeneralType>
				<Format>an..70</Format>
			</DataElement>
		</DataGroup>
		<DataGroup>
			<Name lang="fi">Tavaralähetys</Name>
			<Name lang="sv">Varuförsändelse</Name>
			<Name lang="en">Goods shipment</Name>
			<XPath>GoodsShipment</XPath>
			<MinOccurence>0</MinOccurence>
			<MaxOccurence>1</MaxOccurence>
			<Condition>NC0601</Condition>
			<DataGroup>
				<Name lang="en">Transport charges</Name>
				<XPath>CustomsValuation</XPath>
				<MinOccurence>0</MinOccurence>
				<MaxOccurence>1</MaxOccurence>
				<DataElement>
					<Name lang="en">Transport charges amount</Name>
					<XPath>FreightCharge</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>Decimal</GeneralType>
					<Format>n..16,2</Format>
				</DataElement>
				<DataElement>
					<Name lang="en">Transport charges amount, currency code</Name>
					<XPath>FreightCharge@CurrencyCode</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>String</GeneralType>
					<Format>a3</Format>
				</DataElement>
			</DataGroup>
			<DataGroup>
				<Name lang="en">IOSS</Name>
				<XPath>DomesticDutyTaxParty</XPath>
				<MinOccurence>0</MinOccurence>
				<MaxOccurence>1</MaxOccurence>
				<DataElement>
					<Name lang="en">IOSS VAT no.</Name>
					<XPath>Identification</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>TIN</GeneralType>
					<Format>an..17</Format>
				</DataElement>
			</DataGroup>
			<DataGroup>
				<Name lang="en">Location of goods/warehouse</Name>
				<XPath>Warehouse</XPath>
				<MinOccurence>1</MinOccurence>
				<MaxOccurence>1</MaxOccurence>
				<DescriptionLine lang="en">Data required from 2019 onward.</DescriptionLine>
				<DataElement>
					<Name lang="fi">Varaston tunniste</Name>
					<Name lang="sv">Lageridentifierare</Name>
					<Name lang="en">Warehouse identifier</Name>
					<XPath>Identification</XPath>
					<MinOccurence>1</MinOccurence>
					<EUCDM>2/7</EUCDM>
					<GeneralType>String</GeneralType>
					<Format>an..35</Format>
					<DescriptionLine lang="en">Data required from 2019 onward.</DescriptionLine>
				</DataElement>
				<DataElement>
					<Name lang="en">Date of arrival</Name>
					<XPath>Arrival</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>String</GeneralType>
					<Format>date</Format>
				</DataElement>
			</DataGroup>
			<DataGroup>
				<Name lang="fi">Vientimaa</Name>
				<Name lang="sv">Exportland</Name>
				<Name lang="en">Country of export</Name>
				<XPath>ExportCountry</XPath>
				<MinOccurence>0</MinOccurence>
				<MaxOccurence>1</MaxOccurence>
				<DataElement>
					<Name lang="fi">Vientimaan koodi</Name>
					<Name lang="sv">Kod för exportland</Name>
					<Name lang="en">Country of export code</Name>
					<XPath>Country</XPath>
					<MinOccurence>1</MinOccurence>
					<GeneralType>CountryCode</GeneralType>
					<Codelist>CL008</Codelist>
					<Format>a2</Format>
				</DataElement>
			</DataGroup>
			<DataGroup>
				<Name lang="fi">Edeltävät asiakirjat</Name>
				<Name lang="sv">Tidigare dokument</Name>
				<Name lang="en">Previous documents</Name>
				<XPath>PreviousDocument</XPath>
				<MinOccurence>1</MinOccurence>
				<MaxOccurence>1</MaxOccurence>
				<DescriptionLine lang="en">Data required from 2019 onward.</DescriptionLine>
				<DataElement>
					<Name lang="fi">Tavaraerän tunniste</Name>
					<Name lang="sv">Varupartiidentifierare</Name>
					<Name lang="en">Goods item identifier</Name>
					<XPath>Line</XPath>
					<MinOccurence>0</MinOccurence>
					<EUCDM>2/1</EUCDM>
					<GeneralType>Integer</GeneralType>
					<Condition>NC0603</Condition>
					<Format>n..5</Format>
				</DataElement>
				<DataElement>
					<Name lang="fi">Edeltävä asiakirjatyyppi</Name>
					<Name lang="sv">Tidigare dokumenttyp</Name>
					<Name lang="en">Previous document type</Name>
					<XPath>Type</XPath>
					<MinOccurence>1</MinOccurence>
					<EUCDM>2/1</EUCDM>
					<GeneralType>String</GeneralType>
					<Codelist>CL014</Codelist>
					<Format>an..3</Format>
					<DescriptionLine lang="en">Data required from 2019 onward.</DescriptionLine>
				</DataElement>
				<DataElement>
					<Name lang="fi">Edeltävän asiakirjan viite</Name>
					<Name lang="sv">Referens till tidigare dokument</Name>
					<Name lang="en">Previous document reference</Name>
					<XPath>Identification</XPath>
					<MinOccurence>1</MinOccurence>
					<EUCDM>2/1</EUCDM>
					<GeneralType>String</GeneralType>
					<Format>an..35</Format>
				</DataElement>
			</DataGroup>
			<DataGroup>
				<Name lang="fi">Tavaraerä</Name>
				<Name lang="sv">Varuparti</Name>
				<Name lang="en">Goods item</Name>
				<XPath>GovernmentAgencyGoodsItem</XPath>
				<MinOccurence>1</MinOccurence>
				<MaxOccurence>99999</MaxOccurence>
				<DataElement>
					<Name lang="fi">Tavaraerän numero</Name>
					<Name lang="sv">Varupartinummer</Name>
					<Name lang="en">Goods item number</Name>
					<XPath>Sequence</XPath>
					<MinOccurence>1</MinOccurence>
					<EUCDM>1/6</EUCDM>
					<GeneralType>Integer</GeneralType>
					<Format>n..5</Format>
				</DataElement>
				<DataGroup>
					<Name lang="fi">Tavara</Name>
					<Name lang="sv">Vara</Name>
					<Name lang="en">Commodity</Name>
					<XPath>Commodity</XPath>
					<MinOccurence>0</MinOccurence>
					<MaxOccurence>1</MaxOccurence>
					<DataElement>
						<Name lang="fi">Tavaran koodi</Name>
						<Name lang="sv">Varukod</Name>
						<Name lang="en">Commodity code</Name>
						<XPath>Classification/Identification</XPath>
						<MinOccurence>1</MinOccurence>
						<GeneralType>NumericalString</GeneralType>
						<Format>an..10</Format>
					</DataElement>
					<DataElement>
						<Name lang="en">Goods value</Name>
						<XPath>InvoiceLine/ItemCharge</XPath>
						<MinOccurence>0</MinOccurence>
						<GeneralType>Decimal</GeneralType>
						<Format>n..16,2</Format>
					</DataElement>
					<DataElement>
						<Name lang="en">Goods value, currency code</Name>
						<XPath>InvoiceLine/ItemCharge@currencyCode</XPath>
						<MinOccurence>0</MinOccurence>
						<GeneralType>String</GeneralType>
						<Format>a3</Format>
					</DataElement>
				</DataGroup>
			</DataGroup>
		</DataGroup>
		<DataGroup>
			<Name lang="fi">Pakkaukset</Name>
			<Name lang="sv">Förpackningar</Name>
			<Name lang="en">Packages</Name>
			<XPath>Packaging</XPath>
			<MinOccurence>1</MinOccurence>
			<MaxOccurence>99</MaxOccurence>
			<DescriptionLine lang="en">Data required from 2019 onward.</DescriptionLine>
			<DataElement>
				<Name lang="en">Marks and numbers</Name>
				<XPath>MarksNumbers</XPath>
				<MinOccurence>0</MinOccurence>
				<EUCDM>6/11</EUCDM>
				<GeneralType>String</GeneralType>
				<Format>an..512</Format>
			</DataElement>
			<DataElement>
				<Name lang="fi">Kolliluku</Name>
				<Name lang="sv">Antal kollin</Name>
				<Name lang="en">Number of packages</Name>
				<XPath>Quantity</XPath>
				<MinOccurence>1</MinOccurence>
				<EUCDM>6/10</EUCDM>
				<GeneralType>Integer</GeneralType>
				<Format>n..8</Format>
				<DescriptionLine lang="en">Data required from 2019 onward.</DescriptionLine>
			</DataElement>
			<DataElement>
				<Name lang="fi">Kollien laji</Name>
				<Name lang="sv">Kollislag</Name>
				<Name lang="en">Type of packages</Name>
				<XPath>Type</XPath>
				<MinOccurence>0</MinOccurence>
				<EUCDM>6/9</EUCDM>
				<GeneralType>Integer</GeneralType>
				<Codelist>CL017</Codelist>
				<Format>an2</Format>
			</DataElement>
		</DataGroup>
	</DataGroup>
</Message>

=== FinnishCustoms-SuomenTulli/MIGs/customswarehousing/common/FI428A.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 (x64) (http://www.altova.com) by Finnish Customs (Finnish Customs) -->
<Message xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Message.xsd">
	<Type>FI428A</Type>
	<Name lang="fi">Hyväksymissanoma</Name>
	<Name lang="sv">Meddelande om godtagande</Name>
	<Name lang="en">Acceptance notification</Name>
	<DataGroup>
		<Name lang="fi">Tuontitapahtuma</Name>
		<Name lang="sv">Importåtgärd</Name>
		<Name lang="en">Import operation</Name>
		<XPath>FI428A</XPath>
		<MinOccurence>1</MinOccurence>
		<MaxOccurence>1</MaxOccurence>
		<DataElement>
			<Name lang="fi">MRN</Name>
			<Name lang="sv">MRN</Name>
			<Name lang="en">MRN</Name>
			<XPath>FunctionalReference@function="MRN"</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>MRN</GeneralType>
			<Format>an18</Format>
		</DataElement>
		<DataElement>
			<Name lang="fi">Tapahtuman tunniste</Name>
			<Name lang="sv">Händelsens identifiering</Name>
			<Name lang="en">Case identification</Name>
			<XPath>Identification</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>CaseIdentification</GeneralType>
			<Format>an..22</Format>
		</DataElement>
		<DataElement>
			<Name lang="fi">LRN</Name>
			<Name lang="sv">LRN</Name>
			<Name lang="en">LRN</Name>
			<XPath>FunctionalReference@function="LRN"</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>LRN</GeneralType>
			<Format>an..22</Format>
		</DataElement>
		<DataElement>
			<Name lang="fi">Toissijainen LRN</Name>
			<Name lang="sv">Sekundär LRN</Name>
			<Name lang="en">Additional LRN</Name>
			<XPath>FunctionalReference@function="AdditionalLRN"</XPath>
			<MinOccurence>0</MinOccurence>
			<GeneralType>LRN</GeneralType>
			<Format>an..22</Format>
		</DataElement>
		<DataElement>
			<Name lang="fi">Kielikoodi</Name>
			<Name lang="sv">Språkkod</Name>
			<Name lang="en">Language code</Name>
			<XPath>Language</XPath>
			<MinOccurence>1</MinOccurence>
			<GeneralType>LanguageCode</GeneralType>
			<Codelist>CL012</Codelist>
			<Format>a2</Format>
		</DataElement>
		<DataGroup>
			<Name lang="fi">Ilmoitus</Name>
			<Name lang="sv">Underrättelse</Name>
			<Name lang="en">Notification</Name>
			<XPath>Notification</XPath>
			<MinOccurence>1</MinOccurence>
			<MaxOccurence>1</MaxOccurence>
			<DataElement>
				<Name lang="fi">Ilmoituksen tyyppi</Name>
				<Name lang="sv">Underrättelsens typ</Name>
				<Name lang="en">Notification type</Name>
				<XPath>Type</XPath>
				<MinOccurence>1</MinOccurence>
				<GeneralType>LanguageCode</GeneralType>
				<Format>an..100</Format>
			</DataElement>
			<DataElement>
				<Name lang="fi">Ilmoituksen päiväys ja aika</Name>
				<Name lang="sv">Underrättelsens datum och tid</Name>
				<Name lang="en">Notification date and time</Name>
				<XPath>Notification</XPath>
				<MinOccurence>1</MinOccurence>
				<GeneralType>DateTime</GeneralType>
				<Format>dateTime</Format>
			</DataElement>
		</DataGroup>

	</DataGroup>
</Message>
