=== FinnishCustoms-SuomenTulli/MIGs/customswarehousing/common/rulesconditions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2018 (x64) (http://www.altova.com) by Finnish Customs (Finnish Customs) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="RulesConditions">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="RulesConditionsType"/>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="RulesConditionsType">
		<xs:sequence>
			<xs:element name="RuleCondition" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="ID"/>
						<xs:element name="DescriptionLine" maxOccurs="unbounded">
							<xs:complexType>
								<xs:simpleContent>
									<xs:extension base="xs:string">
										<xs:attribute name="lang" default="en"/>
									</xs:extension>
								</xs:simpleContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== FinnishCustoms-SuomenTulli/MIGs/CourierMail/common/rulesconditions.xml
<?xml version="1.0" encoding="UTF-8"?>
<RulesConditions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="RulesConditions.xsd">
	<RuleCondition>
		<ID>NC0601</ID>
		<DescriptionLine lang="en">IF 'Availabe for clearance' = '1'</DescriptionLine>
		<DescriptionLine lang="en">  THEN This data group / data element = 'R'</DescriptionLine>
		<DescriptionLine lang="en">  ELSE it cannot be used</DescriptionLine>
	</RuleCondition>
	<RuleCondition>
		<ID>NC0602</ID>
		<DescriptionLine lang="en">IF 'Availabe for clearance' = '1'</DescriptionLine>
		<DescriptionLine lang="en">  THEN This data group / data element = 'O'</DescriptionLine>
		<DescriptionLine lang="en">  ELSE it cannot be used</DescriptionLine>
	</RuleCondition>
	<RuleCondition>
		<ID>NC0603</ID>
		<DescriptionLine lang="en">IF Previous document is an Arex MRN</DescriptionLine>
		<DescriptionLine lang="en">  THEN This data element = 'R'</DescriptionLine>
		<DescriptionLine lang="en">  ELSE it cannot be used</DescriptionLine>
	</RuleCondition>
</RulesConditions>
